### ISSUE TITLE
Handle deleted files

### ISSUE THREAD

**Issue by divs1210** [hugit-project/hugit#38]
- [x] show unstaged deleted files
- [x] show staged deleted files.
- [x] Add another session to status view called Deleted
- [x] On selecting Deleted option, should show list of deleted files.
- [x] Show staged/unstaged files differently.
- [x] unstage deleted files
- [x] stage deleted files
- [x] undelete file 
- [x] should check if selected file is staged, and not stage it again
- [x] should check if selected file is unstaged, and not unstage it again

**Comment by Manisha38** [comment]
Fixed all the subtasks. Please check @divs1210

**Comment by divs1210** [comment]
Fixed in #44
