### ISSUE TITLE
Files view does not respect :selected

### ISSUE THREAD

**Issue by divs1210** [hugit-project/hugit#55]
**Reproduce**
1. modify 2 files
2. go to the `Unstaged` files view
3. select the second file on the list
4. go back to files view
5. pointer is pointing at first file (it should be pointing at second) 

**Thoughts**
- We should replace the `navigable-list` in files view with a `scrollable-list`, as the no. of files can be large. This might also fix the issue automatically.
- If the above doesn't fix the issue, we should investigate why the `:selected` key isn't being set/respected in files view.

**Comment by kumar88kanishk** [comment]
Ok
